export const mockUp = [
  {
    id: 1,
    searchCount: 5,
    sku: "AP-IP1100-0064-BLK",
    brand: "Apple",
    model: "iPhone 11",
    capacity: "64GB",
    color: "Black",
    price: "8010$",
    currency: "USD",
  },
  {
    id: 1,
    searchCount: 10,
    sku: "AP-IP1100-0128-BLK",
    brand: "Apple",
    model: "iPhone 11",
    capacity: "128GB",
    color: "Black",
    price: "8010$",
    currency: "USD",
  },
  {
    id: 1,
    searchCount: 12,
    sku: "AP-IP1200-0064-BLK",
    brand: "Apple",
    model: "iPhone 12",
    capacity: "64GB",
    color: "Black",
    price: "8010$",
    currency: "USD",
  },
  {
    id: 1,
    searchCount: 5,
    sku: "AP-IP0800-0064-BLK",
    brand: "Apple",
    model: "iPhone 12",
    capacity: "64GB",
    color: "Black",
    price: "8010$",
    currency: "USD",
  },
];
